### ISSUE TITLE
Can I use gradle to add your lib to my project?

### ISSUE THREAD

**Issue by Ricardo1980** [jefflinwood/ParseQueryAdapterWithPositions#1]
Hello!
I'm an android beginner.
Can I use gradle to add your lib to my project?
Or just copy ParseItemPositionQueryAdapter.java to my project?
Thanks.

**Comment by jefflinwood** [comment]
Hi,

I haven't set this up to be a lib yet for Gradle, so your best bet is to just copy the ParseItemPositionQueryAdapter.java class to your project. Best of luck!
